### ISSUE TITLE
As a user, I want data loader and data exporter templates for Microsoft SQL Server

### ISSUE THREAD

**Issue by tommydangerous** [mage-ai/mage-ai#1510]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cbieberstein** [comment]
You will find that compared to many other RDBMSs data load in sql server is very slow.  Microsoft provides a CLI tool to help with bulk data import but it's got its own caveats.  There's a wrapper library called BCPandas that uses it which may be a source of workarounds.  If you find something better I'd love to know because I hit this problem daily.

**Comment by tommydangerous** [comment]
@cbieberstein thank you so much for the info, will keep looking and keep this in mind. Will update you on our progress. Great suggestion as well!

**Comment by tommydangerous** [comment]
@cbieberstein thank you so much for the info, will keep looking and keep this in mind. Will update you on our progress. Great suggestion as well!

**Comment by wangxiaoyou1993** [comment]
This feature has been released: https://docs.mage.ai/integrations/databases/MicrosoftSQLServer
