### ISSUE TITLE
Wrong Docs URL on Data Exporter - Python Goocle Cloud Storage 

### ISSUE THREAD

**Issue by ReynaldoMR3** [mage-ai/mage-ai#1705]
**Describe the bug**
Wrong URL for the python data exporter regarding google cloud storage.

**To Reproduce**
1. Load a new data exporter selecting python and google cloud storage
2. Click on the Docs: https://github.com/mage-ai/mage-ai/blob/master/docs/blocks/data_loading.md#googlecloudstorage
3. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/55258674/211131782-148dcf44-87f6-4a15-99b2-21de68afd160.png)

**Comment by tommydangerous** [comment]
👀

**Comment by tommydangerous** [comment]
Thank you for reporting, will fix asap.

**Comment by johnson-mage** [comment]
Hi @ReynaldoMR3, the links should have been fixed in https://github.com/mage-ai/mage-ai/pull/1696. Can you update to the latest version of Mage (v0.7.60+) and see if new blocks have working docs links? Existing block files in your project may still have the old link since those retain the same content.

For reference, you can check the [docs here](https://docs.mage.ai/design/data-loading#googlecloudstorage) for info on the GCS data exporters.

**Comment by ReynaldoMR3** [comment]
Thanks! Everything looking fine 👍
