### ISSUE TITLE
File browser context menu is cut off

### ISSUE THREAD

**Issue by johnson-mage** [mage-ai/mage-ai#3800]
**Describe the bug**
- File browser context menu is cut off when right-clicking towards bottom of window.
- Need to position file browser context menu within viewport (e.g. if the context menu is opened at the bottom of the window) so that it is not cut off.

**To Reproduce**
1. Go to `/files` endpoint or any pipeline's "Edit" page.
2. Expand folders so there is a folder/file at the very bottom of the window (shrink window height if necessary).
3. Right-click one of the last items at the bottom of the window.
4. Context menu should be cut off.

**Expected behavior**
Context menu should not be cut off (e.g. should appear above the cursor instead of below it).

**Screenshots**
![file browser context menu bottom of window](https://github.com/mage-ai/mage-ai/assets/78053898/3f0d331a-2ddb-444b-ae20-331d8651f4ad)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 0.9.36

**Comment by mattppal** [comment]
@edmondwinston 

Our FileBrowser component lives at: `mage_ai/frontend/components/FileBrowser/index.tsx`

In the `mage_ai/frontend/components/FileBrowser/Folder.tsx` file, there’s a prop called `onContextMenu` that is used for opening up the context menu when right-clicking in the file browser 😄

**Comment by edmondwinston** [comment]
@johnson-mage 

PR created since this is a UI bug, but for the long term, I've noticed [here](https://github.com/mage-ai/mage-ai/blob/04d8ebf4d0bcac32399bc1fe2d4ee9971160194d/mage_ai/frontend/components/FileBrowser/index.tsx#L401) and [here](https://github.com/mage-ai/mage-ai/blob/04d8ebf4d0bcac32399bc1fe2d4ee9971160194d/mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx#L188-L206l) are both trying to position the context menu (well, the latter does not actually affect anything - all calculated values were 0s when I logged, but isn't that the point), so I'm I misunderstanding anything, or is this a good chance to beautify my records with another PR?

**Comment by johnson-mage** [comment]
> @johnson-mage
> 
> PR created since this is a UI bug, but for the long term, I've noticed [here](https://github.com/mage-ai/mage-ai/blob/04d8ebf4d0bcac32399bc1fe2d4ee9971160194d/mage_ai/frontend/components/FileBrowser/index.tsx#L401) and [here](https://github.com/mage-ai/mage-ai/blob/04d8ebf4d0bcac32399bc1fe2d4ee9971160194d/mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx#L188-L206l) are both trying to position the context menu (well, the latter does not actually affect anything - all calculated values were 0s when I logged, but isn't that the point), so I'm I misunderstanding anything, or is this a good chance to beautify my records with another PR?

@edmondwinston I believe the logic for both of those links are necessary, since I think the first one makes sure the context menu is not cut off on the x-axis, and the second positions _nested_ flyout menus, so the calculated values might appear 0 for a context menu, but if it's used as a dropdown menu with nested submenus, the calculated values would be non-zero.

**Comment by edmondwinston** [comment]
@johnson-mage 

Thanks for the clarification! Another question, what led to your decision of building your own UI blocks instead of using a library? Like the context/submenu, for example, we'd only to pass the items if we were using a prebuilt one, instead of manually calculating styles using the depth.
