### ISSUE TITLE
Timezone for Cron Scheduler

### ISSUE THREAD

**Issue by jeremytanjianle** [mage-ai/mage-ai#3942]
**Is your feature request related to a problem? Please describe.**
From my current experiments, it seems that the scheduler is UTC only. 

Daylight savings can cause the pipeline to run in an unintended time.

if the scheduler has timezone in built into it, it can be robust to daylight savings and is also intuitive for international schedules.

**Describe the solution you'd like**
Timezone for scheduler.

**Describe alternatives you've considered**
API based triggers?

PS loving the mage-Ai experience

**Comment by johnson-mage** [comment]
@jeremytanjianle Do you have the "Display local timezone" setting enabled in your project settings page (see screenshot below for example)? If you do, have you tried using a cron expression for one of your pipeline triggers? For example (in the second screenshot), I use `30 8 * * *` as the custom cron expression so that my next pipeline run starts tomorrow at 8:30 AM PST, as reflected in `Next run date`. There are some limitations to this, such as no special characters in the cron expression as mentioned in the note while editing the trigger, but maybe it can help for your use case. We still use UTC time for the scheduler, but this might help with converting timezones in the UI.

![image](https://github.com/mage-ai/mage-ai/assets/78053898/3941054f-506d-4c65-8175-80eb04ebef56)
![image](https://github.com/mage-ai/mage-ai/assets/78053898/82b0ae09-fba4-4756-bc87-f5707da0c3e9)
![image](https://github.com/mage-ai/mage-ai/assets/78053898/625e0487-41a5-4c3f-9de7-12b36034c869)

**Comment by johnson-mage** [comment]
@jeremytanjianle We currently do not support multiple timezones for different triggers. What's your use case? Or can you give more details in regards to a "multiple timezone" feature?

**Comment by johnson-mage** [comment]
Closing since this issue was addressed in my previous [comment](https://github.com/mage-ai/mage-ai/issues/3942#issuecomment-1804397405)
