### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by Pyt-Sergei** [mage-ai/mage-ai#4601]
Path: /guides/blocks/detach-blocks
there is no such an option "Detach" of block in the newest version pf mage-ai

**Comment by johnson-mage** [comment]
@Pyt-Sergei Is your block being used by more than 1 pipeline? If it is not, the "Detach block" feature will not be visible, since it's there to avoid unintentionally modifying other pipelines. In Step 3 of the doc, it says `Blocks that are not shared by any other pipelines do not have the option to detach itself.`.

I just checked the app on our demo website (demo.mage.ai) and do see that the "Detach" feature is still present. Note that the block in the screenshot below is used by 2 pipelines:
![image](https://github.com/mage-ai/mage-ai/assets/78053898/04628063-b463-49fb-ab46-cd17974a5c61)
