### ISSUE TITLE
[BUG] SQL aliases are ignored

### ISSUE THREAD

**Issue by chrisafl** [mage-ai/mage-ai#4692]
### Mage version

v0.9.65 (demo.mage.ai)

### Describe the bug

At least when using a transformer SQL block, column aliases are ignored.

### To reproduce

1. Load some data (I used the restaurant tutorial from the mage.ai website)
2. Create a SQL Transformer
3. Attempt to alias a column

### Expected behavior

The SQL engine and output of the block should respect defined aliases. I noticed it when I tried to create a chart in a dashboard and source the data from that SQL block.

### Screenshots

![image](https://github.com/mage-ai/mage-ai/assets/7001706/394ed953-85d0-4de7-8500-6eae6778017d)

### Operating system

Windows 11, Edge

**Comment by chrisafl** [comment]
This is the pipeline I am using if you want to see for yourself:
https://demo.mage.ai/pipelines/exciting_wildflower

**Comment by wangxiaoyou1993** [comment]
Thanks for providing the example. We'll fix it.

**Comment by dy46** [comment]
hey @chrisafl, I believe this is happening because you created the table without an alias, and now are using the `Append` write policy option. If you change the alias after already creating the table and then try to append the data to the table, the column names may not be changed.

I'm going to close this issue for now, but if that is not what happened, you can open it up again.
