### ISSUE TITLE
[BUG] Next Run Date calculation error

### ISSUE THREAD

**Issue by geoff-rathmell** [mage-ai/mage-ai#5029]
### Mage version

0.9.70

### Describe the bug

Mage is not calculating the next run date correctly when I use a time expression for a late-night run such as '0 23 * * mon' the Next run date preview says "At 11:00 PM, only on Monday" which is expected. But when I save the trigger the Next Run datetime corresponds to the wrong **date**.

2024-05-**05**T23:00:00-05:00 << NOT CORRECT, this is 11PM SUNDAY

If I use a cron time just a little bit earlier in the day such as '0 15 * * mon' 3PM Mondays, it calculated the next run datetime correctly:

2024-05-**06**T15:00:00-05:00

### To reproduce

Create / Edit a trigger

Select Custom

Insert a CRON expression where the expected runtime would be later in the day IE some time between 9pm and midnight. '0 23 * * mon'

The next run preview text shows OK. "At 11:00 PM, only on Monday"

Save the trigger

Now review the datetime on the Next run date. It is NOT correct
2024-05-**05**T23:00:00-05:00

Expected datetime should be 
2024-05-**06**T23:00:00-05:00

### Expected behavior

Mage should calculate the next run timestamp correctly when scheduling jobs.

### Operating system

- Docker Compose using latest mageai build.
- CDT time on local machine

**Comment by johnson-mage** [comment]
@geoff-rathmell So there are some limitations on the next run preview text for the cron expression when the time is displayed in the local timezone. We always store the dates in the metadata db in UTC, but we convert the UTC time to the local time on the frontend. Right now, only the minute and hour values (without special characters) can be used to accurately convert the cron expression to a human readable expression. If another value is included (e.g. the `mon` in `0 23 * * mon`), it is based in UTC time, which is why the next run date seems off. There's an explanation in the `Note` underneath the input. We haven't been able to prioritize handling the day/month/week values in the cron expression for the human readable text conversion yet, but you can create a new feature request on github so we can keep track of it and put it on our roadmap.

![image](https://github.com/mage-ai/mage-ai/assets/78053898/6e1007c5-cba5-4811-8fa4-152f8106d88c)
