### ISSUE TITLE
Why have there been so few recent updates to the platform, is something wrong

### ISSUE THREAD

**Issue by 13129** [mage-ai/mage-ai#5561]
Why have there been so few recent updates to the platform, is something wrong

**Comment by tommydangerous** [comment]
Hello @13129!

We do make updates to Mage OSS but we don’t always build brand new versions since that requires a lot of backwards compatibility testing, so the large releases have been a bit slower than usual. We’ve also had to split some of our engineering resources to support the companies on Mage Pro, the fully managed service, where we maintain the infrastructure, guarantee uptime, automatically scale your workloads to handle any volume of pipeline runs, automatically upgrade new versions of Mage Pro only features, monitor your production pipelines, and provide enterprise level support.

We do love hearing community feature requests and prioritizing those in OSS. Do you have any particular feature requests in mind?

**Comment by mindesclabs** [comment]
Hi,

Regarding _upgrade new versions of Mage Pro only features_, is there somewhere a list of features that are available only in the pro version? It would be helpful to know what are benefits of pro if there was somewhere comparison between oss and pro...
